name: swifty_proteins_42
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.1.1
  webview_flutter: ^4.13.0
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3
  local_auth: ^2.1.6
  shared_preferences: ^2.5.3
  share_plus: ^7.2.2
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add this assets section
  assets:
    - assets/ligands.txt
    - assets/app_icon.png
